import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/components/layout/layout.layout";
import { createContext, useEffect, useState } from "react";

export const DailyContext: any = createContext({});

const inter = Inter({ subsets: ["latin"] });

let mapper = {
  shift1: 8,
  shift2: 2,
  shift3: 3,
  shift4: 1,
};

let dayMapper = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export default function Home() {
  const [employesTimeList, setEmployesTimeList] = useState([
    {
      name: "Brad",
      hours:0
    },
    {
      name: "Pete",
      hours:0
    },
    {
      name: "Jesse",hours:0
    },
    {
      name: "Greg",hours:0
    },
    {
      name: "Cameron",hours:0
    },
    {
      name: "Junwoo",hours:0
    },
  ]);

  const [employesList, setEmpolyeeList] = useState([
    {
      name: "Brad",
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
    {
      name: "Pete",
      
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
    {
      name: "Jesse",
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
    {
      name: "Greg",
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
    {
      name: "Cameron",
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
    {
      name: "Junwoo",
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
  ]);

  const [shiftList, setShiftList] = useState([
    {
      name: "shift1",
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
    {
      name: "shift2",
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
    {
      name: "shift3",
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
    {
      name: "shift4",
      Mon: [],
      Tue: [],
      Wed: [],
      Thu: [],
      Fri: [],
      Sat: [],
      Sun: [],
    },
  ]);
  const [shiftTimeList, setShiftTimeList] = useState([
    {
      name: "shift1",
      hours:0,
    },
    {
      name: "shift2",
      hours:0,
    },
    {
      name: "shift3",
      hours:0,
    },
    {
      name: "shift4",
      hours:0,
    },
  ]);

  const [dailyForecast, setDailyForecast] = useState([
    { cost: 0, hours: 0 },
    { cost: 0, hours: 0 },
    { cost: 0, hours: 0 },
    { cost: 0, hours: 0 },
    { cost: 0, hours: 0 },
    { cost: 0, hours: 0 },
    { cost: 0, hours: 0 },
  ]);

  useEffect(() => {
    for (let k = 0; k < 7; k++) {
      let hours = 0;
      for (let i = 0; i < employesList.length; i++) {
        // @ts-ignore.
        for (let j = 0; j < employesList[i][dayMapper[k]].length; j++) {
          // @ts-ignore.
          hours += mapper[employesList[i][dayMapper[k]][j].shiftName];
        }
      }
      let dummy = [...dailyForecast];
      dummy[k].hours = hours;
      dummy[k].cost = hours * 25;
      setDailyForecast(dummy);
    }

    for (let i = 0; i < employesList.length; i++) {
      let hours = 0;

      for (let k = 0; k < 7; k++) {
        // @ts-ignore.
        for (let j = 0; j < employesList[i][dayMapper[k]].length; j++) {
          // @ts-ignore.
          hours += mapper[employesList[i][dayMapper[k]][j].shiftName];
        }
      }
      employesTimeList[i].hours = hours
      setEmployesTimeList([...employesTimeList])
    }

    for (let i = 0; i < shiftList.length; i++) {
      let hours = 0;
      for (let k = 0; k < 7; k++) {
        // @ts-ignore.
        hours += shiftList[i][dayMapper[k]].length * mapper[shiftList[i].name]
      }
      shiftTimeList[i].hours = hours
      setShiftTimeList([...shiftTimeList])
    }
  }, [employesList, shiftList]);

  return (
    <>
      <DailyContext.Provider
        value={{
          employesList,
          shiftTimeList,
          setEmpolyeeList,
          shiftList,
          setShiftList,
          dailyForecast,
          employesTimeList,
        }}
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout />
      </DailyContext.Provider>
    </>
  );
}
